"""empty message

Revision ID: 0e0473e03789
Revises: 3107bcfa0a77
Create Date: 2021-10-11 16:54:13.262297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0e0473e03789"
down_revision = "3107bcfa0a77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("ext", sa.String(length=10), nullable=False),
        sa.Column("mime_type", sa.String(length=50), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=1024), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("_created_on", sa.DateTime(), nullable=True),
        sa.Column("_updated_on", sa.DateTime(), nullable=True),
        sa.Column("_created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["_created_by"], ["contacts.id"], onupdate="CASCADE", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "contacts", sa.Column("avatar_id", sa.String(length=10), nullable=True)
    )
    op.create_foreign_key(None, "contacts", "files", ["avatar_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.drop_column("contacts", "avatar_id")
    op.drop_table("files")
    # ### end Alembic commands ###
