"""empty message

Revision ID: 267bff479e18
Revises: a6dde790a25c
Create Date: 2022-07-18 01:34:09.183009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "267bff479e18"
down_revision = "a6dde790a25c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    email_priority = postgresql.ENUM(
        "TRANSACTIONAL",
        "CONSTITUTIONAL",
        "MEMBERSHIP",
        "MARKETING",
        "REPORT",
        name="email_priority",
    )
    email_priority.create(op.get_bind())

    op.alter_column(
        "committees", "access_level", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "contacts", "payments_paused", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.add_column("emails", sa.Column("message", sa.Text(), nullable=True))
    op.add_column(
        "emails", sa.Column("template", sa.String(length=1024), nullable=False)
    )
    op.add_column("emails", sa.Column("priority", email_priority, nullable=False))
    op.drop_column("emails", "type")
    op.drop_column("emails", "text")
    op.drop_column("emails", "html")
    op.alter_column("wiki_text", "body", existing_type=sa.TEXT(), nullable="False")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("wiki_text", "body", existing_type=sa.TEXT(), nullable=False)
    op.add_column(
        "emails", sa.Column("html", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "emails", sa.Column("text", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "emails",
        sa.Column("type", sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    )
    op.drop_column("emails", "priority")
    op.drop_column("emails", "template")
    op.drop_column("emails", "message")
    op.alter_column(
        "contacts", "payments_paused", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "committees", "access_level", existing_type=sa.INTEGER(), nullable=True
    )

    op.execute("DROP TYPE email_priority;")
    # ### end Alembic commands ###
