"""empty message

Revision ID: 2d2744b40d23
Revises: 760948caf1d5
Create Date: 2022-01-18 09:08:30.124192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2d2744b40d23"
down_revision = "760948caf1d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact_attributes")
    op.add_column("files", sa.Column("public_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "public_url")
    op.create_table(
        "contact_attributes",
        sa.Column("contact_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("key", sa.VARCHAR(length=15), autoincrement=False, nullable=False),
        sa.Column("val", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "_created_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "_updated_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name="contact_attributes_contact_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("key", name="contact_attributes_pkey"),
    )
    # ### end Alembic commands ###
