"""empty message

Revision ID: 37c2805f2f39
Revises: 267bff479e18
Create Date: 2022-07-18 02:14:39.502688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "37c2805f2f39"
down_revision = "267bff479e18"
branch_labels = None
depends_on = None


def upgrade():
    email_status = postgresql.ENUM(
        "DRAFT",
        "SCHEDULED",
        "SENT",
        "ARCHIVED",
        "RENDERING",
        "SENDING",
        name="email_status",
    )
    email_status.create(op.get_bind())

    op.add_column("emails", sa.Column("_status", email_status, nullable=True))
    op.drop_column("emails", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "emails",
        sa.Column(
            "status",
            postgresql.ENUM("DRAFT", "SCHEDULED", "SENT", "ARCHIVED", name="statuses"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("emails", "_status")
    # ### end Alembic commands ###
