"""empty message

Revision ID: 392fddfad2cd
Revises: 7da760040b10
Create Date: 2021-10-14 00:38:05.210816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "392fddfad2cd"
down_revision = "7da760040b10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("abbreviation", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("abbreviation"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "committees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("abbreviation", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("abbreviation"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "branch_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=True),
        sa.Column("postcode", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "branch_officers",
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("role_title", sa.String(length=255), nullable=True),
        sa.Column("held_since", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("branch_id", "contact_id"),
    )
    op.create_table(
        "committee_members",
        sa.Column("committee_id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("role_title", sa.String(length=255), nullable=False),
        sa.Column("joined", sa.Date(), nullable=False),
        sa.Column("left", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["committee_id"], ["committees.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("committee_id", "contact_id"),
    )
    op.add_column("contacts", sa.Column("postcode", sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "postcode")
    op.drop_table("committee_members")
    op.drop_table("branch_officers")
    op.drop_table("branch_areas")
    op.drop_table("committees")
    op.drop_table("branches")
    # ### end Alembic commands ###
