"""empty message

Revision ID: 3cd6567b4287
Revises: 844afab1552f
Create Date: 2022-02-01 12:12:32.637932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cd6567b4287'
down_revision = '844afab1552f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CHAIR', 'SEC', 'TRES', 'TRUST', 'MEM', 'DEL', 'REP', 'SREP', 'ORG', 'LREP', name='roletypes'), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.Enum('COMMITTEE', 'BRANCH', name='unittypes'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('held_since', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'contact_id')
    )
    op.create_table('attendables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uprn', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('MEETING', 'ER', 'CLASS', 'PUB', 'PREP', 'SOC', 'MS', 'POL', 'OTHER', name='eventtypes'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('first_occurance', sa.Date(), nullable=False),
    sa.Column('last_occurance', sa.Date(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('DAYS', 'WEEKS', 'MONTHS', 'YEARS', 'NTH_WEEK_OF_MONTH', 'DAY_OF_MONTH', 'NTH_MONTH_OF_YEAR', name='periods'), nullable=False),
    sa.ForeignKeyConstraint(['uprn'], ['addresses.uprn'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsvp_list',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('occurance', sa.Integer(), nullable=False),
    sa.Column('response', sa.Enum('OKAY', 'NA', name='responses'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['attendables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'contact_id')
    )
    op.drop_table('committee_members')
    
    op.drop_table('branch_officers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_officers',
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('held_since', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ends_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='branch_officers_branch_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='branch_officers_contact_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('branch_id', 'contact_id', name='branch_officers_pkey')
    )
   
    op.create_table('committee_members',
    sa.Column('committee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('joined', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('left', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], name='committee_members_committee_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='committee_members_contact_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('committee_id', 'contact_id', name='committee_members_pkey')
    )
    op.drop_table('rsvp_list')
    op.drop_table('attendables')
    op.drop_table('roles')
    # ### end Alembic commands ###
