"""empty message

Revision ID: 5fdf12fd9014
Revises: 8567a07e817d
Create Date: 2022-05-12 01:13:55.115818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5fdf12fd9014"
down_revision = "8567a07e817d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("challenges")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("token", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("contact_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("last4", sa.VARCHAR(length=4), autoincrement=False, nullable=True),
        sa.Column("sms", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("email", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name="challenges_contact_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name="challenges_pkey"),
    )
    # ### end Alembic commands ###
