"""empty message

Revision ID: 71eab3d6ad7e
Revises: 3e1334a4f677
Create Date: 2021-10-28 16:35:10.580361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71eab3d6ad7e"
down_revision = "3e1334a4f677"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_tokens",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("onboarding_tokens")
    # ### end Alembic commands ###
