"""empty message

Revision ID: 72af127614b6
Revises: b6192b364060
Create Date: 2021-10-10 23:20:48.181698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72af127614b6'
down_revision = 'b6192b364060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('_created_on', sa.DateTime(), nullable=True),
    sa.Column('_updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(length=255), nullable=True),
    sa.Column('family_name', sa.String(length=255), nullable=True),
    sa.Column('other_names', sa.String(length=255), nullable=True),
    sa.Column('first_language', sa.String(length=20), nullable=True),
    sa.Column('pronouns', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('membership_number', sa.String(length=15), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('membership_type', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('consents',
    sa.Column('_created_on', sa.DateTime(), nullable=True),
    sa.Column('_updated_on', sa.DateTime(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group', sa.String(length=25), nullable=False),
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('source', sa.String(length=25), nullable=True),
    sa.Column('expires', sa.Date(), nullable=True),
    sa.Column('wording', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'consent_id')
    )
    op.create_table('contact_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('uprn', sa.String(length=15), nullable=True),
    sa.Column('custom_address', sa.Text(), nullable=True),
    sa.Column('owner_from', sa.Date(), nullable=True),
    sa.Column('owner_until', sa.Date(), nullable=True),
    sa.Column('occupier_from', sa.Date(), nullable=True),
    sa.Column('occupier_until', sa.Date(), nullable=True),
    sa.Column('tenant_from', sa.Date(), nullable=True),
    sa.Column('tenant_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_addresses_id'), 'contact_addresses', ['id'], unique=False)
    op.create_table('contact_emails',
    sa.Column('address', sa.String(length=1024), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('contact_numbers',
    sa.Column('number', sa.String(length=15), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_numbers')
    op.drop_table('contact_emails')
    op.drop_index(op.f('ix_contact_addresses_id'), table_name='contact_addresses')
    op.drop_table('contact_addresses')
    op.drop_table('consents')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
