"""empty message

Revision ID: 760948caf1d5
Revises: 71eab3d6ad7e
Create Date: 2021-11-07 23:14:21.784836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "760948caf1d5"
down_revision = "71eab3d6ad7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_attributes",
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=15), nullable=False),
        sa.Column("val", sa.String(length=255), nullable=False),
        sa.Column("_created_on", sa.DateTime(), nullable=True),
        sa.Column("_updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact_attributes")
    # ### end Alembic commands ###
