"""empty message

Revision ID: 7da760040b10
Revises: 0e0473e03789
Create Date: 2021-10-13 23:58:21.739078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7da760040b10"
down_revision = "0e0473e03789"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_roles",
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("contact_id", "name"),
    )
    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=1024), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("html", sa.Text(), nullable=True),
        sa.Column("send_after", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "SCHEDULED", "SENT", "ARCHIVED", name="statuses"),
            nullable=True,
        ),
        sa.Column("_created_on", sa.DateTime(), nullable=True),
        sa.Column("_updated_on", sa.DateTime(), nullable=True),
        sa.Column("_created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["_created_by"], ["contacts.id"], onupdate="CASCADE", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "email_recipients",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CONTACT", "BRANCH", "COMMITTEE", "SECTION", name="recipient_types"
            ),
            nullable=False,
        ),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["emails.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "type", "recipient_id"),
    )
    op.add_column(
        "contacts", sa.Column("password_hash", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "contacts", sa.Column("account_blocked", sa.Boolean(), nullable=False)
    )
    op.add_column("files", sa.Column("bucket", sa.String(length=50), nullable=True))
    op.add_column("files", sa.Column("key", sa.String(length=1024), nullable=True))
    op.add_column("files", sa.Column("delete_after", sa.DateTime(), nullable=True))
    op.drop_column("files", "path")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("path", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    )
    op.drop_column("files", "delete_after")
    op.drop_column("files", "key")
    op.drop_column("files", "bucket")
    op.drop_column("contacts", "account_blocked")
    op.drop_column("contacts", "password_hash")
    op.drop_table("email_recipients")
    op.drop_table("emails")
    op.drop_table("auth_roles")
    # ### end Alembic commands ###
