"""empty message

Revision ID: a7171e65bb62
Revises: 5d2d2abbc237
Create Date: 2021-10-15 16:04:41.307314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7171e65bb62'
down_revision = '5d2d2abbc237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('barcode_img_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['barcode_img_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_coupon_id', sa.String(length=255), nullable=True),
    sa.Column('base_rate', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('STANDARD', 'ASSOCIATE', 'AFFILIATE', name='subs_types'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'NEW', 'CANCELLED', 'REJECTED', 'PAYMENT_FAILED', 'LAPSED', 'ARREARS', 'SUSPENDED', 'INCOMPLETE', name='subs_statuses'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_object_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('JOINED', 'PAYMENT', 'FAILED_PAYMENT', 'AD_HOC_PAYMENT', 'CANCELLED', 'ISSUED_CARD', 'RENEWED', 'SUSPENDED', 'REJECTED', name='activity_codes'), nullable=True),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_stripe_object_id'), 'activity', ['stripe_object_id'], unique=False)
    op.alter_column('contact_addresses', 'uprn',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_addresses', 'uprn',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_activity_stripe_object_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_table('subscriptions')
    op.drop_table('cards')
    # ### end Alembic commands ###
