"""empty message

Revision ID: a758d1a41c56
Revises: b0c70b5cb3bf
Create Date: 2021-10-22 01:07:18.226473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a758d1a41c56'
down_revision = 'b0c70b5cb3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_id', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_pages_category'), 'pages', ['category'], unique=False)
    op.create_foreign_key(None, 'contacts', 'files', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_pages_category'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
