"""empty message

Revision ID: ad7569119c3c
Revises: ce3402b8476b
Create Date: 2022-02-14 22:11:09.973596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7569119c3c'
down_revision = 'ce3402b8476b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
