"""empty message

Revision ID: b6192b364060
Revises: 6dffa1f70a5f
Create Date: 2021-10-10 23:04:47.095402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6192b364060"
down_revision = "6dffa1f70a5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
