"""empty message

Revision ID: c8dc8dcff57a
Revises: 2d2744b40d23
Create Date: 2022-01-21 16:27:36.877453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8dc8dcff57a'
down_revision = '2d2744b40d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
