"""empty message

Revision ID: ccf3a0a55f58
Revises: 7845daf266f7
Create Date: 2022-04-17 21:00:31.020437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccf3a0a55f58'
down_revision = '7845daf266f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=52), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=52), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SUBS', 'DONA', 'SALE', 'ADHC', 'RNEW', name='payment_types'), nullable=False),
    sa.Column('method_type', sa.String(length=20), nullable=True),
    sa.Column('method_last4', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hmo_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uprn', sa.BigInteger(), nullable=True),
    sa.Column('license_no', sa.String(length=20), nullable=True),
    sa.Column('holder_name', sa.String(length=100), nullable=True),
    sa.Column('holder_address', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('max_persons', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uprn'], ['addresses.uprn'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('onboarding_tokens')
    op.drop_index('ix_activity_stripe_object_id', table_name='activity')
    op.drop_table('activity')
    op.drop_table('subscriptions')
    op.add_column('cards', sa.Column('status', sa.String(length=10), nullable=True))
    op.add_column('contact_availability', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('contact_availability', 'timestamp')
    op.drop_column('contacts', 'postcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('postcode', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('contact_availability', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('contact_availability', 'start_time')
    op.drop_column('cards', 'status')
    op.create_table('subscriptions',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('renewal_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('stripe_price_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_coupon_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('base_rate', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('STANDARD', 'ASSOCIATE', 'AFFILIATE', name='subs_types'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'NEW', 'CANCELLED', 'REJECTED', 'PAYMENT_FAILED', 'LAPSED', 'ARREARS', 'SUSPENDED', 'INCOMPLETE', name='subs_statuses'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='subscriptions_contact_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('activity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stripe_object_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('JOINED', 'PAYMENT', 'FAILED_PAYMENT', 'AD_HOC_PAYMENT', 'CANCELLED', 'ISSUED_CARD', 'RENEWED', 'SUSPENDED', 'REJECTED', name='activity_codes'), autoincrement=False, nullable=True),
    sa.Column('subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='activity_contact_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='activity_subscription_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='activity_pkey')
    )
    op.create_index('ix_activity_stripe_object_id', 'activity', ['stripe_object_id'], unique=False)
    op.create_table('onboarding_tokens',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='onboarding_tokens_contact_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='onboarding_tokens_pkey')
    )
    op.drop_table('memberships')
    op.drop_table('hmo_register')
    op.drop_table('payments')
    # ### end Alembic commands ###
