"""empty message

Revision ID: cdc2288d5318
Revises: eba46e08d967
Create Date: 2022-04-18 22:46:45.549928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cdc2288d5318"
down_revision = "eba46e08d967"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "contact_addresses_uprn_fkey", "contact_addresses", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "contact_addresses",
        "addresses",
        ["uprn"],
        ["uprn"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column("contacts", "lives_at", type_=sa.BigInteger)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contact_addresses", type_="foreignkey")
    op.create_foreign_key(
        "contact_addresses_uprn_fkey",
        "contact_addresses",
        "addresses",
        ["uprn"],
        ["uprn"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.alter_column("contacts", "lives_at", type_=sa.Integer)
    # ### end Alembic commands ###
