"""empty message

Revision ID: e6ae7ee38bb4
Revises: ad7569119c3c
Create Date: 2022-02-14 22:28:09.801298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ae7ee38bb4'
down_revision = 'ad7569119c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('duration', sa.FLOAT(precision=8, asdecimal=True, decimal_return_scale=6), nullable=True))
    op.drop_column('requests', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('requests', 'duration')
    # ### end Alembic commands ###
