"""empty message

Revision ID: f7de189ba8a1
Revises: b4817bbd5383
Create Date: 2022-04-29 00:37:01.817216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7de189ba8a1"
down_revision = "b4817bbd5383"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("cards_barcode_img_id_fkey", "cards", type_="foreignkey")
    op.drop_column("cards", "barcode_img_id")
    op.add_column(
        "contacts",
        sa.Column("stripe_payment_method_id", sa.String(length=52), nullable=True),
    )
    op.add_column("contacts", sa.Column("membership_rate", sa.Integer(), nullable=True))
    op.alter_column(
        "memberships", "status", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "memberships", "status", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.drop_column("contacts", "membership_rate")
    op.drop_column("contacts", "stripe_payment_method_id")
    op.add_column(
        "cards",
        sa.Column(
            "barcode_img_id", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "cards_barcode_img_id_fkey", "cards", "files", ["barcode_img_id"], ["id"]
    )
    op.drop_table("donations")
    # ### end Alembic commands ###
