"""empty message

Revision ID: ff567cf89dec
Revises: 9d133e300ff1
Create Date: 2021-10-14 00:55:07.146470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff567cf89dec"
down_revision = "9d133e300ff1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_deliveries",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("_created_on", sa.DateTime(), nullable=True),
        sa.Column("_updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], onupdate="CASCADE", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["message_id"], ["emails.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "contact_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_deliveries")
    # ### end Alembic commands ###
